config/routes.rb
Rails.application.routes.draw do
resources :welcomes
  root 'welcomes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email,:password , confirmation:true
  validates :email_confirmation, presence: true, on: :create
  validates :password, presence: true

end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :session_check, except: [:create,:new]
  before_action :action_check, only:[:new,:create]
  def index
    @user = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def edit
    @user = User.find(params[:id])
  end
  def create
    @user = User.new(usr_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(update_params)
      redirect_to @user
    else
      #Rails.logger.info(@user.errors.messages.inspect)
      render 'edit'
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
  
  private
  def usr_params
    params.require(:user).permit(:name,:email,:email_confirmation,:password,:dob)
  end
  def update_params
    params.require(:user).permit(:name,:email,:dob)
  end
  def session_check
    if session[:user_id].blank?
      redirect_to root_url
    end
  end
  def action_check
    if session[:user_id].present?
      redirect_to user_path(session[:user_id])
    end
  end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :check_session, except:[:create,:new,:index]
  def index
  end
  def new 
    @welcome = Welcome.new
  end
  def create
    @welcome = Welcome.new(wel_params)
    user = User.find_by_email(params[:welcome][:email])
    if user.password == params[:welcome][:password]
        session[:user_id] = user.id
        redirect_to user, notice: "Logged in!"
        else
        @welcome.destroy
        flash.now.alert = "Email or password is invalid"
        render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  private
    def wel_params
      params.require(:welcome).permit(:email,:password)
    end
    def check_session
      if session[:user_id].blank?
        redirect_to root_url
      end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginForm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for @user do |user|%>
  <ul style="list-style-type: none">
  Name: <li><%= user.text_field :name%></li>
  DOB: <li><%= date_select("user","dob",start_year:1972,end_year:2036) %></li>
  Email: <li><%= user.text_field :email%></li>
  <%= user.submit 'Edit Profile'%>
</ul>
<% end %>
<%= link_to 'Back', user_path(@user) %>
<%= link_to 'Signout', welcome_path,method: :delete%>

app/views/users/index.html.erb
<table>
  <th>
    <td>Name</td>
    <td>Email</td>
  </th>
<tr>
  <% @user.each do |show|%>
  <td><%= show.name %></td>
  <td><%= show.email %></td>
  <td><%= link_to 'Edit', edit_user_path(show) %></td>
  <td><%= link_to 'Show', user_path(show) %></td>
  <td><%= link_to 'Delete', user_path(show), method: :delete, data:{confirm: "Are You sure"} %></td>
</tr> 
<% end %>
</table>
<%= link_to 'Signout', welcome_path(@user),method: :delete%>

app/views/users/new.html.erb
<%= form_for @user do |user|%>
  <ul style="list-style-type: none">
  Name: <li><%= user.text_field :name%></li>
  ODB: <li><%= date_select("user","dob",start_year:1972,end_year:2036) %></li>
  Email: <li><%= user.text_field :email%></li>
  Confirm_email: <li><%= user.text_field :email_confirmation %></li>
  password: <li><%= user.password_field :password %></li>
  <%= user.submit 'Create Profile'%>
</ul>
<% end %>

app/views/users/show.html.erb
<table>
  <tr>
    <td><%= @user.name %> ||</td>
    <td><%= @user.email %></td>
    <td><%= link_to 'edit' , edit_user_path(@user) %></td>
  </tr>
</table>
<%= link_to 'All Profile', users_path %>
<%= link_to 'Signout', welcome_path(@user),method: :delete%>

app/views/welcomes/index.html.erb
<h1>Welcome</h1>
<%=  link_to 'Sign up', new_user_path %>||
<%= link_to 'sign in', new_welcome_path %>

app/views/welcomes/new.html.erb
<%= form_for @welcome do |welcome|%>
  Email: <%= welcome.text_field :email %><br />
  password: <%= welcome.password_field :password %><br />
  <%= welcome.submit 'SignIN' %>
<% end %>
<%= link_to 'signUP', new_user_path %>